version: "3"

services:
    
    node-app2:
        image: yolix/node-app:v1
        ports:
            - 3001:8080
        networks: 
            - node-app2

    node-app:
        image: yolix/node-app:v1
        deploy:
            replicas: 2
        networks: 
            - node-app
    
    nginx:
        image: nginx
        ports: 
            - 80:80
        networks: 
            - node-app
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        
networks: 
    node-app:
        driver: bridge
    node-app2:
        driver: bridge

        

